[theme]
base = "dark"
primaryColor = "#c98bdb"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[server]
headless = true
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200

[client]
toolbarMode = "viewer"
